### ISSUE TITLE
Beautifier erased all my files

### ISSUE THREAD

**Issue by fabre-thibaud** [philsturgeon/coffeescript-beautifier#1]
I don't understand. I tried using your beautifier and all my files are gone.

Did you write unit tests ?

**Comment by philsturgeon** [comment]
![image](https://cloud.githubusercontent.com/assets/67381/6834454/b202f8c0-d30a-11e4-8069-12b2b57c802d.png)

**Comment by fabre-thibaud** [comment]
:clap:

**Comment by philsturgeon** [comment]
I don't need unit tests, it works just fine over here.
