### ISSUE TITLE
Help, my coffeescript just vanished!

### ISSUE THREAD

**Issue by jrgifford** [philsturgeon/coffeescript-beautifier#7]
Hey, so I followed the directions in the readme (TERRIBLE LICENSING CHOICE BY THE WAY, DBAD IS A TERRIBLE LICENSE THAT RESTRICTS OUR FREEDOMS), and now my coffeescript is gone. 

help please?

**Comment by philsturgeon** [comment]
Actually the DBAD license gives you full freedom to do anything you want, it just means that I might think you're a dick, which - as far as I know - will not hold much weight in court.

Dunno about your files though. Check Time Machine?
